# Using https://github.com/marketplace/actions/vue-to-github-pages github action
name: Build Vue, push to gh-pages branch, and make available for github pages
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'sungineers'
        reponame: 'sungineers.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        cname: 'sungineers.io'